export const challenges = {
	ff5kOneStepP1: {
		challengeName: "Foxx Funded 5k oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 5000,
		challengePrice: 53,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff10kOneStepP1: {
		challengeName: "Foxx Funded 10k oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 10000,
		challengePrice: 89,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff25kOneStepP1: {
		challengeName: "Foxx Funded 25k oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 25000,
		challengePrice: 219,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff50kOneStepP1: {
		challengeName: "Foxx Funded 50k oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 50000,
		challengePrice: 299,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff100kOneStepP1: {
		challengeName: "Foxx Funded 100k oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 100000,
		challengePrice: 455,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff200kOneStepP1: {
		challengeName: "Foxx Funded 200k oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 200000,
		challengePrice: 806,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff300kOneStepP1: {
		challengeName: "Foxx Funded 300k oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 300000,
		challengePrice: 1118,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},

	ff5kOneStepF: {
		challengeName: "Foxx Funded 5k oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 5000,
		challengePrice: 53,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff10kOneStepF: {
		challengeName: "Foxx Funded 10k oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 10000,
		challengePrice: 89,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff25kOneStepF: {
		challengeName: "Foxx Funded 25k oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 25000,
		challengePrice: 219,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff50kOneStepF: {
		challengeName: "Foxx Funded 50k oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 50000,
		challengePrice: 299,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff100kOneStepF: {
		challengeName: "Foxx Funded 100k oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 100000,
		challengePrice: 455,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff200kOneStepF: {
		challengeName: "Foxx Funded 200k oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 200000,
		challengePrice: 806,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff300kOneStepF: {
		challengeName: "Foxx Funded 300k oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 300000,
		challengePrice: 1118,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},

	// 2-step
	ff5kTwoStepP1: {
		challengeName: "Foxx Funded 5k twoStep",
		challengeType: "twoStep",
		currentPhase: "phase1",
		accountSize: 5000,
		challengePrice: 49,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 10,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase2",
			},
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff10kTwoStepP1: {
		challengeName: "Foxx Funded 10k twoStep",
		challengeType: "twoStep",
		currentPhase: "phase1",
		accountSize: 10000,
		challengePrice: 79,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 10,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase2",
			},
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff25kTwoStepP1: {
		challengeName: "Foxx Funded 25k twoStep",
		challengeType: "twoStep",
		currentPhase: "phase1",
		accountSize: 25000,
		challengePrice: 206,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 10,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase2",
			},
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff50kTwoStepP1: {
		challengeName: "Foxx Funded 50k twoStep",
		challengeType: "twoStep",
		currentPhase: "phase1",
		accountSize: 50000,
		challengePrice: 271,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 10,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase2",
			},
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff100kTwoStepP1: {
		challengeName: "Foxx Funded 100k twoStep",
		challengeType: "twoStep",
		currentPhase: "phase1",
		accountSize: 100000,
		challengePrice: 416,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 10,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase2",
			},
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff200kTwoStepP1: {
		challengeName: "Foxx Funded 200k twoStep",
		challengeType: "twoStep",
		currentPhase: "phase1",
		accountSize: 200000,
		challengePrice: 773,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 10,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase2",
			},
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff300kTwoStepP1: {
		challengeName: "Foxx Funded 300k twoStep",
		challengeType: "twoStep",
		currentPhase: "phase1",
		accountSize: 300000,
		challengePrice: 1079,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 10,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase2",
			},
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},

	ff5kTwoStepP2: {
		challengeName: "Foxx Funded 5k twoStep",
		challengeType: "twoStep",
		currentPhase: "phase2",
		accountSize: 5000,
		challengePrice: 49,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 10,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase2",
			},
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff10kTwoStepP2: {
		challengeName: "Foxx Funded 10k twoStep",
		challengeType: "twoStep",
		currentPhase: "phase2",
		accountSize: 10000,
		challengePrice: 79,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 10,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase2",
			},
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff25kTwoStepP2: {
		challengeName: "Foxx Funded 25k twoStep",
		challengeType: "twoStep",
		currentPhase: "phase2",
		accountSize: 25000,
		challengePrice: 206,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 10,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase2",
			},
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff50kTwoStepP2: {
		challengeName: "Foxx Funded 50k twoStep",
		challengeType: "twoStep",
		currentPhase: "phase2",
		accountSize: 50000,
		challengePrice: 271,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 10,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase2",
			},
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff100kTwoStepP2: {
		challengeName: "Foxx Funded 100k twoStep",
		challengeType: "twoStep",
		currentPhase: "phase2",
		accountSize: 100000,
		challengePrice: 416,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 10,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase2",
			},
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff200kTwoStepP2: {
		challengeName: "Foxx Funded 200k twoStep",
		challengeType: "twoStep",
		currentPhase: "phase2",
		accountSize: 200000,
		challengePrice: 773,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 10,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase2",
			},
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff300kTwoStepP2: {
		challengeName: "Foxx Funded 300k twoStep",
		challengeType: "twoStep",
		currentPhase: "phase2",
		accountSize: 300000,
		challengePrice: 1079,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 10,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase1",
			},
			phase2: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 30,
				offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
				stage: "phase2",
			},
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},

	ff5kTwoStepF: {
		challengeName: "Foxx Funded 5k twoStep",
		challengeType: "twoStep",
		currentPhase: "funded",
		accountSize: 5000,
		challengePrice: 49,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff10kTwoStepF: {
		challengeName: "Foxx Funded 10k twoStep",
		challengeType: "twoStep",
		currentPhase: "funded",
		accountSize: 10000,
		challengePrice: 79,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff25kTwoStepF: {
		challengeName: "Foxx Funded 25k twoStep",
		challengeType: "twoStep",
		currentPhase: "funded",
		accountSize: 25000,
		challengePrice: 206,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff50kTwoStepF: {
		challengeName: "Foxx Funded 50k twoStep",
		challengeType: "twoStep",
		currentPhase: "funded",
		accountSize: 50000,
		challengePrice: 271,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff100kTwoStepF: {
		challengeName: "Foxx Funded 100k twoStep",
		challengeType: "twoStep",
		currentPhase: "funded",
		accountSize: 100000,
		challengePrice: 416,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff200kTwoStepF: {
		challengeName: "Foxx Funded 200k twoStep",
		challengeType: "twoStep",
		currentPhase: "funded",
		accountSize: 200000,
		challengePrice: 773,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff300kTwoStepF: {
		challengeName: "Foxx Funded 300k twoStep",
		challengeType: "twoStep",
		currentPhase: "funded",
		accountSize: 300000,
		challengePrice: 1079,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 1,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},

	// Instant
	ff5kInstantF: {
		challengeName: "Foxx Funded 5k Instant Funding",
		challengeType: "funded",
		currentPhase: "funded",
		accountSize: 5000,
		challengePrice: 209,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff10kInstantF: {
		challengeName: "Foxx Funded 10k Instant Funding",
		challengeType: "funded",
		currentPhase: "funded",
		accountSize: 10000,
		challengePrice: 345,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff25kInstantF: {
		challengeName: "Foxx Funded 25k Instant Funding",
		challengeType: "funded",
		currentPhase: "funded",
		accountSize: 25000,
		challengePrice: 699,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff50kInstantF: {
		challengeName: "Foxx Funded 50k Instant Funding",
		challengeType: "funded",
		currentPhase: "funded",
		accountSize: 50000,
		challengePrice: 1099,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
	ff100kInstantF: {
		challengeName: "Foxx Funded 100k Instant Funding",
		challengeType: "funded",
		currentPhase: "funded",
		accountSize: 100000,
		challengePrice: 2199,
		platform: "Match-Trader",
		broker: "Match-Trader",
		status: "active",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 5,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 30,
				offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
				stage: "funded",
			},
		},
		__v: 0,
	},
};
