//  Standard Challenge DATA

export const sc5k = {
	challengeName: "5K Standard Challenge",
	challengeType: "twoStep",
	accountSize: 5000,
	challengePrice: 35,
	platform: "MT5",
	broker: "Haven Capital Grp",
	refundable: true,
	challengeStages: {
		phase1: {
			maxDailyDrawdown: 5,
			maxDrawdown: 12,
			tradingPeriod: "unlimited",
			profitTarget: 10,
			minTradingDays: 5,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "phase1",
		},
		phase2: {
			maxDailyDrawdown: 5,
			maxDrawdown: 10,
			tradingPeriod: "unlimited",
			profitTarget: 5,
			minTradingDays: 10,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "phase2",
		},
		funded: {
			maxDailyDrawdown: 5,
			maxDrawdown: 12,
			tradingPeriod: "unlimited",
			profitTarget: null,
			minTradingDays: 5,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "funded",
		},
	},
};

export const sc10 = {
	challengeName: "10K Standard Challenge",
	challengeType: "twoStep",
	accountSize: 10000,
	challengePrice: 63,
	platform: "MT5",
	broker: "Haven Capital Grp",
	refundable: true,
	challengeStages: {
		phase1: {
			maxDailyDrawdown: 5,
			maxDrawdown: 12,
			tradingPeriod: "unlimited",
			profitTarget: 10,
			minTradingDays: 5,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "phase1",
		},
		phase2: {
			maxDailyDrawdown: 5,
			maxDrawdown: 10,
			tradingPeriod: "unlimited",
			profitTarget: 5,
			minTradingDays: 10,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "phase2",
		},
		funded: {
			maxDailyDrawdown: 5,
			maxDrawdown: 12,
			tradingPeriod: "unlimited",
			profitTarget: null,
			minTradingDays: 5,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "funded",
		},
	},
};

export const sc25 = {
	challengeName: "25K Standard Challenge",
	challengeType: "twoStep",
	accountSize: 25000,
	challengePrice: 126,
	platform: "MT5",
	broker: "Haven Capital Grp",
	refundable: true,
	challengeStages: {
		phase1: {
			maxDailyDrawdown: 5,
			maxDrawdown: 12,
			tradingPeriod: "unlimited",
			profitTarget: 10,
			minTradingDays: 5,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "phase1",
		},
		phase2: {
			maxDailyDrawdown: 5,
			maxDrawdown: 10,
			tradingPeriod: "unlimited",
			profitTarget: 5,
			minTradingDays: 10,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "phase2",
		},
		funded: {
			maxDailyDrawdown: 5,
			maxDrawdown: 12,
			tradingPeriod: "unlimited",
			profitTarget: null,
			minTradingDays: 5,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "funded",
		},
	},
};

export const sc50 = {
	challengeName: "50K Standard Challenge",
	challengeType: "twoStep",
	accountSize: 50000,
	challengePrice: 209.3,
	platform: "MT5",
	broker: "Haven Capital Grp",
	refundable: true,
	challengeStages: {
		phase1: {
			maxDailyDrawdown: 5,
			maxDrawdown: 12,
			tradingPeriod: "unlimited",
			profitTarget: 10,
			minTradingDays: 5,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "phase1",
		},
		phase2: {
			maxDailyDrawdown: 5,
			maxDrawdown: 10,
			tradingPeriod: "unlimited",
			profitTarget: 5,
			minTradingDays: 10,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "phase2",
		},
		funded: {
			maxDailyDrawdown: 5,
			maxDrawdown: 12,
			tradingPeriod: "unlimited",
			profitTarget: null,
			minTradingDays: 5,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "funded",
		},
	},
};

export const sc100 = {
	challengeName: "100K Standard Challenge",
	challengeType: "twoStep",
	accountSize: 100000,
	challengePrice: 364,
	platform: "MT5",
	broker: "Haven Capital Grp",
	refundable: true,
	challengeStages: {
		phase1: {
			maxDailyDrawdown: 5,
			maxDrawdown: 12,
			tradingPeriod: "unlimited",
			profitTarget: 10,
			minTradingDays: 5,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "phase1",
		},
		phase2: {
			maxDailyDrawdown: 5,
			maxDrawdown: 10,
			tradingPeriod: "unlimited",
			profitTarget: 5,
			minTradingDays: 10,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "phase2",
		},
		funded: {
			maxDailyDrawdown: 5,
			maxDrawdown: 12,
			tradingPeriod: "unlimited",
			profitTarget: null,
			minTradingDays: 5,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "funded",
		},
	},
};

export const sc200 = {
	challengeName: "200K Standard Challenge",
	challengeType: "twoStep",
	accountSize: 200000,
	challengePrice: 686,
	platform: "MT5",
	broker: "Haven Capital Grp",
	refundable: true,
	challengeStages: {
		phase1: {
			maxDailyDrawdown: 5,
			maxDrawdown: 12,
			tradingPeriod: "unlimited",
			profitTarget: 10,
			minTradingDays: 5,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "phase1",
		},
		phase2: {
			maxDailyDrawdown: 5,
			maxDrawdown: 10,
			tradingPeriod: "unlimited",
			profitTarget: 5,
			minTradingDays: 10,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "phase2",
		},
		funded: {
			maxDailyDrawdown: 5,
			maxDrawdown: 12,
			tradingPeriod: "unlimited",
			profitTarget: null,
			minTradingDays: 5,
			newsTrading: true,
			weekendHolding: true,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "funded",
		},
	},
};

// Instant Funding DATA

export const if10k = {
	challengeName: "10K Instant Funding",
	challengeType: "funded",
	accountSize: 10000,
	challengePrice: 240,
	platform: "MT5",
	broker: "Haven Capital Grp",
	refundable: true,
	challengeStages: {
		phase1: null,
		phase2: null,
		funded: {
			maxDailyDrawdown: 4,
			maxDrawdown: 8,
			tradingPeriod: "unlimited",
			profitTarget: null,
			minTradingDays: 5,
			newsTrading: false,
			weekendHolding: false,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "funded",
		},
	},
};

export const if25k = {
	challengeName: "25K Instant Funding",
	challengeType: "funded",
	accountSize: 25000,
	challengePrice: 480,
	platform: "MT5",
	broker: "Haven Capital Grp",
	refundable: true,
	challengeStages: {
		phase1: null,
		phase2: null,
		funded: {
			maxDailyDrawdown: 4,
			maxDrawdown: 8,
			tradingPeriod: "unlimited",
			profitTarget: null,
			minTradingDays: 5,
			newsTrading: false,
			weekendHolding: false,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "funded",
		},
	},
};

export const if50k = {
	challengeName: "50K Instant Funding",
	challengeType: "funded",
	accountSize: 50000,
	challengePrice: 800,
	platform: "MT5",
	broker: "Haven Capital Grp",
	refundable: true,
	challengeStages: {
		phase1: null,
		phase2: null,
		funded: {
			maxDailyDrawdown: 4,
			maxDrawdown: 8,
			tradingPeriod: "unlimited",
			profitTarget: null,
			minTradingDays: 5,
			newsTrading: false,
			weekendHolding: false,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "funded",
		},
	},
};

export const if100k = {
	challengeName: "100K Instant Funding",
	challengeType: "funded",
	accountSize: 100000,
	challengePrice: 1440,
	platform: "MT5",
	broker: "Haven Capital Grp",
	refundable: true,
	challengeStages: {
		phase1: null,
		phase2: null,
		funded: {
			maxDailyDrawdown: 4,
			maxDrawdown: 8,
			tradingPeriod: "unlimited",
			profitTarget: null,
			minTradingDays: 5,
			newsTrading: false,
			weekendHolding: false,
			drawdownType: "Equity/balance",
			consistencyRule: true,
			leverage: 30,
			stage: "funded",
		},
	},
};
