//  Standard Challenge DATA

export const foxFunded25step1 = {
	challengeName: "Fox Funded 25k oneStep",
	challengeType: "oneStep",
	accountSize: 25000,
	challengePrice: 219,
	platform: "Match-Trader",
	broker: "Match-Trader",
	status: "active",
	challengeStages: {
		phase1: {
			maxDailyDrawdown: 4,
			maxDrawdown: 8,
			tradingPeriod: "360 Days",
			profitTarget: 7,
			minTradingDays: 5,
			drawdownType: "equity-based",
			profitSpilt: "90/10",
			payouts: false,
			leverage: 30,
			offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
			stage: "phase1",
		},
		phase2: null,
		funded: {
			maxDailyDrawdown: 4,
			maxDrawdown: 8,
			tradingPeriod: "Unlimited",
			profitTarget: null,
			minTradingDays: 1,
			drawdownType: "equity-based",
			profitSpilt: "90/10",
			payouts: true,
			leverage: 30,
			offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
			stage: "funded",
		},
	},
	__v: 0,
};

export const foxFunded25step2 = {
	challengeName: "Fox Funded 25k twoStep",
	challengeType: "twoStep",
	accountSize: 25000,
	challengePrice: 206,
	platform: "Match-Trader",
	broker: "Match-Trader",
	status: "active",
	challengeStages: {
		phase1: {
			maxDailyDrawdown: 4,
			maxDrawdown: 8,
			tradingPeriod: "360 Days",
			profitTarget: 10,
			minTradingDays: 5,
			drawdownType: "equity-based",
			profitSpilt: "90/10",
			payouts: false,
			leverage: 30,
			offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
			stage: "phase1",
		},
		phase2: {
			maxDailyDrawdown: 4,
			maxDrawdown: 8,
			tradingPeriod: "360 Days",
			profitTarget: 7,
			minTradingDays: 5,
			drawdownType: "equity-based",
			profitSpilt: "90/10",
			payouts: false,
			leverage: 30,
			offerUUID: "1abefa9d-ed32-4c20-8ac6-a063ec4dd3e0",
			stage: "phase1",
		},
		funded: {
			maxDailyDrawdown: 4,
			maxDrawdown: 8,
			tradingPeriod: "Unlimited",
			profitTarget: null,
			minTradingDays: 1,
			drawdownType: "equity-based",
			profitSpilt: "90/10",
			payouts: true,
			leverage: 30,
			offerUUID: "dde5740b-c23e-4980-a616-eade125dc7bb",
			stage: "funded",
		},
	},
};
